/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2024-2025. All rights reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * 编辑component id
 */
export namespace UiComponentIdOfEditor {
  // tool bar 返回
  export const TOP_BACK: string = 'petalClip_topToolBar_back';

  // tool bar 编辑
  export const TOP_EDIT: string = 'petalClip_topToolBar_edit';

  // tool bar 保存
  export const TOP_SAVE: string = 'petalClip_topToolBar_save';

  // 裁剪-旋转
  export const CROP_TOOL_ROTATE_BTN: string = 'petalclip_CropTool_rotateBtn';

  // 裁剪-镜像
  export const CROP_TOOL_MIRROR_BTN: string = 'petalclip_CropTool_mirrorBtn';

  // 裁剪-旋转角度
  export const CROP_TOOL_RULER_SCROLLER: string = 'petalclip_CropTool_rulerScroller';

  // 裁剪-旋转角度-拖拽
  export const RULER_BAR_RULER_SCROLLER: string = 'petalclip_RulerBar_rulerScroller';

  // 裁剪-智能校正-未选中
  export const CROP_TAB_INTELLIGENT_CORRECTION_OFF: string = 'cropTab_intelligentCorrection_off';

  // 裁剪-智能校正-选中
  export const CROP_TAB_INTELLIGENT_CORRECTION_ON: string = 'cropTab_intelligentCorrection_on';

  // 裁剪-旋转-未选中
  export const CROP_TAB_ROTATION_OFF: string = 'cropTab_rotation_off';

  // 裁剪-旋转-选中
  export const CROP_TAB_ROTATION_ON: string = 'cropTab_rotation_on';

  // 裁剪-水平校正-未选中
  export const CROP_TAB_HORIZONTAL_CORRECTION_OFF: string = 'cropTab_horizontalCorrection_off';

  // 裁剪-水平校正-选中
  export const CROP_TAB_HORIZONTAL_CORRECTION_ON: string = 'cropTab_horizontalCorrection_on';

  // 裁剪-垂直校正-未选中
  export const CROP_TAB_VERTICAL_CORRECTION_OFF: string = 'cropTab_verticalCorrection_off';

  // 裁剪-垂直校正-选中
  export const CROP_TAB_VERTICAL_CORRECTION_ON: string = 'cropTab_verticalCorrection_on';

  // 裁剪-比例-未选中
  export const CROP_TAB_RATIO_OFF: string = 'cropTab_ratio_off';

  // 裁剪-比例-选中
  export const CROP_TAB_RATIO_ON: string = 'cropTab_ratio_on';

  // AI修图-图标
  export const AI_RETOUCH: string = 'petalclip_AiRetouch';

  // 裁剪-整体
  export const BOTTOM_TOOL_BAR_CROP: string = 'petalClip_bottomToolBar_1';

  // 裁剪-图标
  export const BOTTOM_TOOL_BAR_CROP_IMG: string = 'petalClip_bottomToolBar_image_1';

  // 裁剪-文字
  export const BOTTOM_TOOL_BAR_CROP_TEXT: string = 'petalClip_bottomToolBar_text_1';

  // 调节-整体
  export const BOTTOM_TOOL_BAR_REGULATE: string = 'petalClip_bottomToolBar_2';

  // 调节-图标
  export const BOTTOM_TOOL_BAR_REGULATE_IMG: string = 'petalClip_bottomToolBar_image_2';

  // 调节-文字
  export const BOTTOM_TOOL_BAR_REGULATE_TEXT: string = 'petalClip_bottomToolBar_text_2';

  // 滤镜-整体
  export const BOTTOM_TOOL_BAR_FILTER: string = 'petalClip_bottomToolBar_4';

  // 滤镜-图标
  export const BOTTOM_TOOL_BAR_FILTER_IMG: string = 'petalClip_bottomToolBar_image_4';

  // 滤镜-文字
  export const BOTTOM_TOOL_BAR_FILTER_TEXT: string = 'petalClip_bottomToolBar_text_4';

  // 涂鸦-整体
  export const BOTTOM_TOOL_BAR_GRAFFITI: string = 'petalClip_bottomToolBar_7';

  // 涂鸦-图标
  export const BOTTOM_TOOL_BAR_GRAFFITI_IMG: string = 'petalClip_bottomToolBar_image_7';

  // 涂鸦-文字
  export const BOTTOM_TOOL_BAR_GRAFFITI_TEXT: string = 'petalClip_bottomToolBar_text_7';

  // 文字-整体
  export const BOTTOM_TOOL_BAR_TEXT: string = 'petalClip_bottomToolBar_8';

  // 文字-图标
  export const BOTTOM_TOOL_BAR_TEXT_IMG: string = 'petalClip_bottomToolBar_image_8';

  // 文字-文字
  export const BOTTOM_TOOL_BAR_TEXT_TEXT: string = 'petalClip_bottomToolBar_text_8';

  // 马赛克-整体
  export const BOTTOM_TOOL_BAR_MOSAIC: string = 'petalClip_bottomToolBar_9';

  // 马赛克-图标
  export const BOTTOM_TOOL_BAR_MOSAIC_IMG: string = 'petalClip_bottomToolBar_image_9';

  // 马赛克-文字
  export const BOTTOM_TOOL_BAR_MOSAIC_TEXT: string = 'petalClip_bottomToolBar_text_9';
}