/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2025-2025. All rights reserved.
 */

/* instrument ignore file */

/**
 * 操作定义
 */
export class OperateDefine {
  /**
   * 年宫格滑动速度
   */
  public static readonly GRID_YEAR_FLING_SPEED: number = 5000;

  /**
   * 年宫格横屏状态滑动速度
   */
  public static readonly GRID_YEAR_FLING_SPEED_HORIZONTAL: number = 2000;

  /**
   * 月宫格滑动速度
   */
  public static readonly GRID_MONTH_FLING_SPEED: number = 10000;

  /**
   * 日宫格滑动速度
   */
  public static readonly GRID_DAY_FLING_SPEED: number = 8000;
}